services:
  webapp:
    image: koldi/trackvote_webapp:latest
    build:
      context: ./webapp
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
      - "27017:27017"
    command: ["npm", "run", "start"]
    healthcheck:
      test: ["CMD-SHELL", "node healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  bot:
    image: koldi/trackvote_bot:latest
    build:
      context: ./Bot
      dockerfile: Dockerfile
    depends_on:
      - webapp
    environment:
      - PYTHONUNBUFFERED=0
      - WEBAPP_URL=http://webapp:3000
    command: ["python3", "main.py"]

volumes:
  shared-volume: